name: clearmind_app
description: A Flutter app for journaling with mood-based background colors.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management and basic dependencies
  provider: ^6.1.2

  # Database for local storage
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # UI enhancements
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/happy_bg.jpg
    - assets/images/sad_bg.jpg
    - assets/images/neutral_bg.jpg

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
